### ISSUE TITLE
Add `declaration-property-value-no-unknown` support for SCSS.

### ISSUE THREAD

**Issue by pamelalozano16** [stylelint-scss/stylelint-scss#1017]
Add [`declaration-property-value-no-unknown`](https://github.com/stylelint/stylelint/tree/main/lib/rules/declaration-property-value-no-unknown) support for SCSS features and ignore SassScript.
E.g.
```scss
// Functions
@function get-color() {
   @return #336699;
}
.element {
  color: get-color(); // Unexpected unknown value "get-color" (declaration-property-value-no-unknown)
}

// Variables shorthand values
$var1: 1px;
a {
  margin: 2px $var1; // Cannot parse property value "2px $var1" for property "margin" (declaration-property-value-no-unknown)
}

// Hidden declarations
$rounded-corners: false;
.button {
  border: 1px solid black;
  border-radius: if($rounded-corners, 5px, null); // Cannot parse property value "if($rounded-corners, 5px, null)" for property "border-radius" (declaration-property-value-no-unknown)
}

// Nested properties
.b {
  font: {
    size: red; // No errors
  }
  font-size: red; // Unexpected unknown value "red" for property "font-size" (declaration-property-value-no-unknown)
}
```

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0SAEA1AhgJwJaYCMAbGAZ1VIAsJsAXSzAOylQDdMiBXMgHUYBJ22AIzxUwgA4APANx8+mVMHm0AtjgDmuRmIBM01IJzC5jAL7zGKVADFOjMLVwRGpPgAEAZvcfPGqDRhaAFpIIhoACgBKJT5UePdsIM5sfwBiAGYMgDZsgE480wtGPgA6GBJVGEZaWP9UMJoxQJDG7Giiy2sAOTJaGCgy7U8IYIlMQLr49WwtHVRMTloIKfjUAghaZdUxAAZTNdRliT1pA9RinloVEZqxZRLr2lJcAC8YMSSoUyvLx9uQi93p8Bp0SlY0AAJXBQWD+WBgIg4TBOFxuATYCD2WBQUI0RgwbCkMSeDikGA-RilAhLZb+B7xDbYWDYMSSKQUCBEGHrJFgADW5yZLOC2EwUFwnGJqFwngi-Ex2IGeNShNIABpUABWaSaxicIhEKJgvjWACSNUJEi5KL8fH4EiSnlwUjEPBAxAgAvdlPKulWEtIEiRAE8xNpuQTgmlgA6nS6zCaIagALKYCTo-htaUROJrR24GZh1BpXa7ADsBE8nnVefi5MgzBwxbS2TA5a15agtfq9c4YDAZGlaV0AA5MOWACxanuHKBMQKsktQMAZLXT2drADuOEY2g0YjS1bAwgrfGNlmptHpdfWmAFGkVzDx4SX6gkpRa8uzmoLRYv5iWEBjAgOqIDOiQ3SYFUCAgDAUjQcGMClKQYCkKQoHgC4zoaLBDKoO68H9MwbgIKgADat7uqQtAhiQkatNhuAaMENFMPOzKsWhpF5gAupu7rYAavBkfh8TugiSJiqijBjJiEiErRwTsFwMDBIwoz2PyGlbiUZG0EJMB5sUZiYY2OE2DQ6i0LBABWpAuJhsAZnhebUbR9HaIC3Hum6IBIv0NHugJIA0XRFReXijA4axtDsTguKoehvkEf5KJ9O6fCmWYQA)

**Comment by kristerkari** [comment]
Sure, having that rule with SCSS support would make sense 👍

**Comment by beatrizsmerino** [comment]
This rule generates errors when you use something like this:
```css
box-shadow: inset 0 0 1rem rgba($color-black, 0.5);
border: 0.3rem solid $color-white;
```

The issue arises because the rule cannot recognize a property value as valid when it contains multiple data types (e.g. for the `border` property, `border-width`, `border-style`, and `border-color`) and one of them is a Sass variable. It treats the Sass variable as an unknown or invalid value.

**Comment by balajis-qb** [comment]
When we use a combinded value with scss variable it's throwing an error.

For example, `border: 1px solid $boder-color;` is throwing an error - `declaration-property-value-no-unknown`

But if we define this value in a seperate variable and use means it's working

```
$boder-value: 1px solid $boder-color;
border: $boder-value;

```

This issue arise only when I use `stylelint-config-standard` v37, but if I use v36 the combined values are working.

**Comment by fvwanja** [comment]
I think you are currently already working on it, but just to give you more context if you need it:

From my package.json:

```json
"sass": "^1.83.4",
"stylelint": "^16.13.2",
"stylelint-config-recommended": "^15.0.0",
"stylelint-order": "^6.0.4",
"stylelint-prettier": "^5.0.2",
"stylelint-scss": "^6.10.1",
```

Error message:

`Unexpected unknown value "baseline(4)" for property "padding"  declaration-property-value-no-unknown`

The SCSS code:

```scss
padding: baseline(4) baseline(2);
```

The SCSS function:

```scss
@function baseline($value) {
  @return calc(var(--baseline) * #{$value});
}
```

**Comment by beatrizsmerino** [comment]
I have updated the packages, but if I remove the `declaration-property-value-value-no-unknown` setting, the errors still come up.

<img width="522" alt="Image" src="https://github.com/user-attachments/assets/0175f527-9d94-4db6-9c4c-eb9ba3875e5c" />

<img width="1167" alt="Image" src="https://github.com/user-attachments/assets/01ecc343-d1bc-4c86-b5dd-e387d60aff4f" />

<img width="1134" alt="Image" src="https://github.com/user-attachments/assets/8086b54c-1689-4e15-b17e-596ec53c8a23" />

**Comment by simensol** [comment]
@kristerkari Has this issue been resolved and published to npm? I am using `v6.11.0` of `stylelint-scss` and am encountering the same problem as @beatrizsmerino. Additionally, I am using combined values with SCSS variables similar to @balajis-qb:

```scss
$test: rgb(255 0 0);

.test {
    border: 4px solid $test;
}
```

```bash
test.vue
  310:17  ✖  Cannot parse property value     declaration-property-value-no-unknown
             "4px solid $test" for property
             "border"
```

**Comment by kristerkari** [comment]
@simensol to me it looks like you are running the non-SCSS version of the rule. The SCSS version rule name is `scss/declaration-property-value-no-unknown` instead of the CSS version which is just called `declaration-property-value-no-unknown`.

If you are using some existing config that has the CSS version, you should be able to do something like this in your stylelint config:

```json
"declaration-property-value-no-unknown": null,
"scss/declaration-property-value-no-unknown": true
```

**Comment by simensol** [comment]
@kristerkari Thank you for your suggestion. Your proposed `stylelint` configuration resolves the issue.

The problem occurred when I upgraded `stylelint-config-recommended-vue` from `1.5.0` to `1.6.0` ([compare view](https://github.com/ota-meshi/stylelint-config-recommended-vue/compare/v1.5.0...v1.6.0)). The relevant `stylelint` packages in my `package.json` are:

```bash
  "stylelint": "^16.14.1",
  "stylelint-config-prettier-scss": "^1.0.0",
  "stylelint-config-standard-scss": "^14.0.0",
  "stylelint-config-standard-vue": "^1.0.0",
```

Here is my `stylelint` configuration before your suggested changes regarding `declaration-property-value-no-unknown`:

```yml
extends:
    - stylelint-config-standard-scss
    - stylelint-config-standard-vue/scss
    - stylelint-config-prettier-scss
rules:
    selector-class-pattern:
        - "^(([a-z][a-z0-9]*)(-[a-z0-9]+)*)|(([A-Z][a-z]+)+(_([A-Z][a-z]+)+)*((_[a-z]*))*)$"
    scss/percent-placeholder-pattern:
        - "^(v-(.*))$"
    scss/at-extend-no-missing-placeholder: null
    color-function-notation: ["modern", { "ignore": ["with-var-inside"] }]
    selector-pseudo-class-no-unknown:
        - true
        - ignorePseudoClasses: ["global"]
```

I am confused about why `declaration-property-value-no-unknown` is enabled by default instead of `scss/declaration-property-value-no-unknown`. Is it expected behavior that CSS-only rules are enabled by default and must be explicitly disabled? Or is it a bug in `stylelint-scss` or `stylelint-config-recommended-vue`?

If this is not the appropriate place to discuss this, please guide me on where to raise this issue.
