### ISSUE TITLE
Suggestion: A way to make selector-class-pattern work with Sass union class names (&)

### ISSUE THREAD

**Issue by ArianeBouchardConformit** [stylelint-scss/stylelint-scss#1044]
My team uses [BEM](https://getbem.com/), and we also do a lot of class unions with "&" to save on repetitions. For instance, our code might look like this:

```scss
.my-component {
  &--has-banner-true {
    padding-top: 24px;
  }

  &__title {
    font-size: 2em;
    
    .my-component--has-banner-true & {
      padding-top: 0;
    }
  }
}
```

It would be really nice if there were a way to make sure the format of union classes, such as `&--has-banner-true` (resolves to `.my-component--has-banner-true`) and `&__title` (resolves to `.my-component__title`) matches our naming convention.
