### ISSUE TITLE
Add a new option for `scss/dollar-variable-empty-line-before` after functions

### ISSUE THREAD

**Issue by AlexWayfer** [stylelint-scss/stylelint-scss#1096]
Hello.

I have such code:

```scss
@use "sass:color";

@use "../lib/inputs-with-types";

@use "../colors";
@use "../sizes";

$form-vertical-label-margin: 0.8em;
$form-vertical-input-margin: 0.4em;

@mixin styles {
  /* ... */
}
```

And there are such offenses:

```
assets/styles/components/_forms.scss
  8:1  ✖  Unexpected empty line before $-variable  scss/dollar-variable-empty-line-before
```

The suggestion is to have something like `after-functions` option for `ignore` configuration.
