### ISSUE TITLE
Add a lint for style rules whose selectors are just "&"

### ISSUE THREAD

**Issue by nex3** [stylelint-scss/stylelint-scss#394]
Sometimes mixin authors who don't fully understand how parent selectors work will write `&` as the sole selector for a style rule rather than including properties in the root level of the mixin. We should add a lint to warn them away from this practice. For example:

```scss
@mixin add-color($color) {
  & {
    color: $color;
  }
}
```

is semantically identical to:

```scss
@mixin add-color($color) {
  color: $color;
}
```

/cc @rambleraptor
