### ISSUE TITLE
no-global-function-names does not allow using CSS math functions

### ISSUE THREAD

**Issue by in-in** [stylelint-scss/stylelint-scss#486]
This code causes the error `Expected math.min instead of min   scss/no-global-function-names`

```scss
.foo {
  width: min(300px, 30%);
}
```

Same with the _max()_ function `Expected math.max instead of max   scss/no-global-function-names` 
```scss
.foo {
  width: max(300px, 30%);
}
```

.stylelintrc.js
```js
module.exports = {
  'plugins': [
    'stylelint-scss',
  ],
  'rules': {
    'scss/no-global-function-names': true,
  },
};
```

```json
"stylelint": "13.7.0",
"stylelint-scss": "3.18.0"
```

https://caniuse.com/#feat=css-math-functions

**Comment by kristerkari** [comment]
Looks like the rule need to handle this as a special case. From Sass' docs:

> If a min() or max() function call is valid plain CSS, it will be compiled to a CSS min() or max() call. “Plain CSS” includes nested calls to calc(), env(), var(), min(), or max(), as well as interpolation. As soon as any part of the call contains a SassScript feature like variables or function calls, though, it’s parsed as a call to Sass’s core min() or max() function instead.

https://sass-lang.com/documentation/syntax/special-functions#min-and-max

**Comment by kristerkari** [comment]
Or is this a bug? Does it get solved by changing to use `math.min` and `math.max`, in that case the rule is working correctly.

**Comment by geebru** [comment]
@kristerkari Just confirming that it is a bug in the linter - seems like it needs to check for the values inside `min`, `max`, `clamp`, etc. for anything Sass-specific (variables, functions, etc) and validate against that?

As it stands it's returning errors for valid usages of `max` as a CSS function (not Sass).

**Comment by Donov4n** [comment]
Hi everyone :) Any known workaround for this ?

**Comment by kristerkari** [comment]
@Donov4n As a workaround you could add comments before and after your code to disable the rule for a single block of code, e.g.

```scss
// stylelint-disable scss/no-global-function-names
.foo {
  width: min(300px, 30%);
}
// stylelint-enable scss/no-global-function-names
```

More info: https://stylelint.io/user-guide/ignore-code/
