### ISSUE TITLE
`color-function-notation` show error for scss `rgba` function

### ISSUE THREAD

**Issue by qmhc** [stylelint-scss/stylelint-scss#563]
Will take the `color-function-notation` error when using scss rgba function like:
```scss
.a {
  color: rgba($base-color, 0.8);
}
```

A config `'color-function-notation': 'modern'` extends from `stylelint-config-standard` (using `stylelint-config-standard-scss`), it cannot distinguish rgba between css and scss.
