### ISSUE TITLE
It woud be great to have rules for newlines in parameter definitions and maps

### ISSUE THREAD

**Issue by mirisuzanne** [stylelint-scss/stylelint-scss#579]
for example, enforcing one of:

```scss
@mixin name ($one, $two: default) { … };
@mixin name (
  $one, 
  $two: default
) { … };
```

and for maps, one of:

```scss
$map: (one: value, two: value);
$map: (
  one: value, 
  two: value,
);
```
