### ISSUE TITLE
Lint Reference Usage without namespace

### ISSUE THREAD

**Issue by Sysix** [stylelint-scss/stylelint-scss#595]
Hello,

it would really help when there is a rule for following use case:

```scss
// file a.scss:
@import 'b';
@import 'c';
```

```scss
// file b.scss:
$var1: #000;
```

```scss
// file c.scss:
body {
  color: $var1; <-- should warn
}
```

The solution should be:

```scss
// file c.scss:
@use 'b';

body {
  color: b.$var1;
}
```

This also should check for `@mixins` at other namespaceable keywords.
