### ISSUE TITLE
grid with scss/operator-no-newline-before

### ISSUE THREAD

**Issue by Cedric-ruiu** [stylelint-scss/stylelint-scss#600]
Hello,

I found issue when using `grid-template` with function at the end and with `operator-no-newline-before`.

```scss
.-testSuccess {
  grid-template:
    'bar'
    / 1fr;
}

.-testError {
  grid-template:
    'foo'
    'bar' minmax(0, min-content)
    / 1fr; // here emit error but it's ok
}
```

`Unexpected newline before "/" (scss/operator-no-newline-before)`
