### ISSUE TITLE
scss/annotation-no-unknown

### ISSUE THREAD

**Issue by rehberbey** [stylelint-scss/stylelint-scss#666]
This is my first time using Stylelint. And I realized that while CSS has `annotation-no-unknown` property, **SCSS does not**.
When I activate the main rule, rules like `!default`, `!global` in SCSS cause an error.

```scss
$variable: "first global value";

.content {
  $variable: "second global value" !global;
  //                               ^? Unexpected unknown annotation "!global"
  //                                  (annotation-no-unknown) Stylelintannotation-no-unknown
  content: $variable;
}

.sidebar {
  content: $variable;
}
```
