### ISSUE TITLE
Nested property shorthand error

### ISSUE THREAD

**Issue by rehberbey** [stylelint-scss/stylelint-scss#672]
With SCSS we can write a shorthand property and write the rest of that property to the value of that property. That's fine, but *Stylelint* will throw an error if we assign a value to shorthand.

## Input

```scss
button {
    border: none {
/*  ^? Unexpected nested property "border"
    (scss/declaration-nested-properties)
    Stylelintscss/declaration-nested-properties */
        block-end: 2px solid red;
    /*  ^? Unexpected unknown property "block-end"
        (property-no-unknown)
        Stylelintproperty-no-unknown */
    }
}
```

## Output

```css
button {
  border: none;
  border-block-end: 2px solid red;
}
```
