### ISSUE TITLE
scss/operator-no-unspaced rule fails on negative numbers in interpolated values

### ISSUE THREAD

**Issue by sergeyDevjatov** [stylelint-scss/stylelint-scss#803]
_This is similar issue to #450_

There is no fails
```scss
$fooBarFooBarFooBarFooBarFooBarFooBarFooBarFooBarFooBarFooBarFooBar: color.scale(
  #000000,
  $lightness: -50%,
  $alpha: -50%
);
```

In this case which similar to case above there is fails on $lightness and $alpha values
```scss
$fooBarFooBarFooBarFooBarFooBarFooBarFooBarFooBarFooBarFooBarFooBar: #{color.scale(
    #000000,
    $lightness: -50%,
    $alpha: -50%
  )};
```

In this case there is fail on $lightness value
```scss
$c: #{color.scale(#000000, $lightness: -50%, $alpha: -50%)};
```

It's reproduced with stylelint-scss@4.6.0 and stylelint@15.4.0
