### ISSUE TITLE
`scss/function-no-unknown` doesn't work with interpolation

### ISSUE THREAD

**Issue by LeoMcA** [stylelint-scss/stylelint-scss#817]
Sass requires interpolation when assigning a function's output to a css var: https://sass-lang.com/documentation/breaking-changes/css-vars

e.g. one has to do:
```scss
--background-mark-yellow: #{color.adjust(
    $mdn-color-light-theme-yellow-30,
    $alpha: -0.6
  )};
```

rather than:
```scss
--background-mark-yellow: color.adjust(
  $mdn-color-light-theme-yellow-30,
  $alpha: -0.6
);
```

however, `scss/function-no-unknown` throws an error when using interpolation:
```
✖  Unexpected unknown function "#{color.adjust"  scss/function-no-unknown
```
