### ISSUE TITLE
Add lint for `rtl:ignore` comment directives on nested style rules

### ISSUE THREAD

**Issue by Goodwine** [stylelint-scss/stylelint-scss#893]
# Input
```scss
.foo {
  /* rtl:ignore */
  .bar {
    a: b;
  }
}
```
# Output ([playground](https://sass-lang.com/playground/#eJwzNNRLy89XqOZSUNDXUigqybHKTM/LL0pV0NIHCuklJRaB5RQUEq0UkqyBrFquWgBtYQ00))
```css
.foo {
  /* rtl:ignore */      <------ This was not moved out.
}
.foo .bar {             <------ BUG: This is not ignored by RTLCSS as intended.
  a: b;
}
```
# Context
`/* rtl:ignore */` is an [RTLCSS directive](https://rtlcss.com/learn/usage-guide/control-directives/) which makes RTLCSS skip the subsequent CSS node from being RTL-yfied. For example: `/* rtl:ignore */ .foo { float:left; margin-right: 10px; }` causes both declarations to remain unchanged by RTLCSS.

However, Sass loud comments (`/* */`) within a rule declaration aren't attached to anything. They don't "belong" to the subsequent node. And therefore, when Sass compiles to CSS, it "splits" the directive away from the nested rule block which the author intended as shown in the example above.

And to add a cherry on top, this could lead to a bug if there exists a declaration after the nested rule, like in this example:

```scss
.foo {
  /* rtl:ignore */
  .bar {
    a: b;
  }

  float: left;
}
```
Which produces:
```css
.foo {
  /* rtl:ignore */
  float: left;      <----- BUG 2: This is now ignored by RTLCSS, but that wasn't intended.
}
.foo .bar {
  a: b;
}
```
